spring:
  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      exposed-headers: Content-Type,Authorization
      allow-credentials: true
      max-age: 3600